### GET request with parameter
GET https://httpbin.org/get?show_env=1
Accept: application/json

### Send POST request with json body
POST https://httpbin.org/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}