### Add new vote to a poll
POST http://localhost:{{BACKEND_PORT}}/api/polls/330/vote/{{GUEST_UUID}}
Content-Type: application/json
#Authorization: Bearer {{ACCESS_TOKEN}}

{
  "optionId": 659,
  "vote":  "NO",
  "name": "Julek"
}