### Update poll with id 1
PATCH http://localhost:{{BACKEND_PORT}}/api/polls/25/{{GUEST_UUID}}
Content-Type: application/json
#Authorization: Bearer {{ACCESS_TOKEN}}

{
  "title":  "Poll title GUEST USER UPDATED",
  "description":  "Poll description UPDATED"
}