### Create a new poll
POST http://localhost:{{BACKEND_PORT}}/api/polls
Content-Type: application/json

{
  "title":  "Poll title",
  "description":  "Poll description",
  "timezone":  "Europe/Warsaw",
  "options": [
    {
      "type": "TIME_RANGE",
      "startTime": "2025-01-14T00:00:00.000Z",
      "endTime": "2025-01-14T23:59:59.999Z"
    },
    {
      "type": "DATE",
      "date": "2025-01-14"
    }
  ],
  "settings": {
    "allowOnlyOneVote": false,
    "allowMaybeAnswer": true,
    "hideOthersAnswers": false,
    "voteDeadline": "2025-02-14T12:00:00.000Z"
  }
}